name: Build My APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet
        run: |
          pip install flet
          
      - name: Build APK
        run: |
          # 这一次我们放弃中文名，先保证 APK 成功产出
          flet build apk --project "mynoteapp" --org "com.zak.notes"

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: note-app-apk
          path: build/apk/*.apk
