name: Build My APK
on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许你手动点击开始

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet and Build
        run: |
          pip install flet
          flet build apk --project "我的智能笔记" --org "com.zak.notes"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: note-app-apk
          path: build/apk/*.apk
